# ===============================
# Spring Boot
# ===============================
server.port=8080
# SSL 활성화
server.ssl.enabled=false
# keystore 설정
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-alias=${KEYSTORE_ALIAS}
spring.config.import=optional:file:.env[.properties]
# ===============================
# Database (PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL}?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# ========= Google OAuth2 =========
# spring.security.oauth2.client.registration.google.client-id=
# spring.security.oauth2.client.registration.google.client-secret=
# spring.security.oauth2.client.registration.google.redirect-uri=
# spring.security.oauth2.client.registration.google.scope=
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
# ========= Kakao OAuth2 =========
# spring.security.oauth2.client.registration.kakao.client-id=
# spring.security.oauth2.client.registration.kakao.client-secret= # 선택
# spring.security.oauth2.client.registration.kakao.redirect-uri=
# spring.security.oauth2.client.registration.kakao.authorization-grant-type=
# spring.security.oauth2.client.registration.kakao.scope=
# spring.security.oauth2.client.registration.kakao.client-name=
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
# ========= Apple OAuth2 =========
# Apple 은 나중에 구현
# ===============================
# MyBatis
# ===============================
# mybatis.mapper-locations=classpath:mappers/**/*.xml
# mybatis.configuration.map-underscore-to-camel-case=true
# ===============================
# Devtools
# ===============================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
# ===============================
# JWT secret key
# ===============================
# WARNING: jwt.secret must be provided via VM options or external env
jwt.secret=${jwt.secret}