name: Feature Branch Build Validation

on:
  push:
    branches:
      - "**/feature/**" # 모든 사용자의 feature 브랜치에 대해 푸시 이벤트 트리거
  pull_request:
    branches:
      - "**/feature/**" # feature 브랜치로의 PR 이벤트 트리거

jobs:
  build:
    runs-on: ubuntu-latest  # 최신 우분투 환경에서 실행

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 환경 설정
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # JDK 배포판 (OpenJDK)
          java-version: '17'       # 원하는 Java 버전 (예: 17)

      # 3. Gradle 캐시 설정
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle 빌드 실행
      - name: Build with Gradle
        run: ./gradlew build

      # 5. Gradle 테스트 실행
      - name: Run tests
        run: ./gradlew test
